import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';
import { scale } from './scale';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FC',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: scale(20),
  },
  playerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    height: scale(54),
    borderBottomWidth: 1,
    borderBottomColor: '#EAECEF',
    backgroundColor: colors.white,
  },
  backButton: {
    padding: scale(6),
  },
  playerHeaderTitle: {
    fontSize: scale(16),
    fontWeight: 'bold',
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  playerMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    marginTop: scale(14),
    marginBottom: scale(8),
  },
  playerMetaTitle: {
    fontSize: scale(15),
    fontWeight: 'bold',
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  playerMetaCategory: {
    color: colors.gray,
    fontWeight: 'normal',
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Regular',
  },
  playerMetaDuration: {
    fontSize: scale(12),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  relatedHeader: {
    fontSize: scale(15),
    fontWeight: 'bold',
    color: '#1C1F2A',
    paddingHorizontal: scale(16),
    marginBottom: scale(12),
    fontFamily: 'BricolageGrotesque-Bold',
  },
  relatedList: {
    paddingHorizontal: scale(16),
  },
  relatedCard: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderRadius: scale(12),
    padding: scale(10),
    marginBottom: scale(12),
    borderWidth: 1,
    borderColor: '#EAECEF',
  },
  relatedThumbnailContainer: {
    width: scale(90),
    height: scale(60),
    borderRadius: scale(8),
    overflow: 'hidden',
    position: 'relative',
  },
  relatedThumbnail: {
    width: '100%',
    height: '100%',
  },
  playBadgeSmall: {
    position: 'absolute',
    bottom: scale(4),
    right: scale(4),
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: scale(10),
    padding: scale(4),
  },
  relatedInfo: {
    flex: 1,
    marginLeft: scale(12),
    justifyContent: 'center',
  },
  relatedCategoryLabel: {
    fontSize: scale(10),
    fontWeight: 'bold',
    marginBottom: scale(2),
    fontFamily: 'BricolageGrotesque-Bold',
  },
  relatedTitle: {
    fontSize: scale(12),
    fontWeight: 'bold',
    color: '#1C1F2A',
    marginBottom: scale(4),
    fontFamily: 'BricolageGrotesque-Bold',
  },
  relatedMetaText: {
    fontSize: scale(10),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  heroCard: {
    backgroundColor: '#0D112B',
    borderRadius: scale(16),
    marginHorizontal: scale(16),
    marginTop: scale(16),
    marginBottom: scale(20),
    padding: scale(20),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heroLeft: {
    flex: 1,
    marginRight: scale(12),
  },
  heroBadgesRow: {
    flexDirection: 'row',
    gap: scale(8),
    marginBottom: scale(10),
  },
  badgeContainer: {
    paddingHorizontal: scale(8),
    paddingVertical: scale(3),
    borderRadius: scale(12),
  },
  badgeText: {
    color: colors.white,
    fontSize: scale(9),
    fontWeight: 'bold',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  heroTitle: {
    color: colors.white,
    fontSize: scale(17),
    fontWeight: 'bold',
    marginBottom: scale(6),
    fontFamily: 'BricolageGrotesque-Bold',
  },
  heroSub: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Regular',
  },
  heroPlayButton: {
    width: scale(44),
    height: scale(44),
    borderRadius: scale(22),
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryContainer: {
    flexDirection: 'row',
    paddingHorizontal: scale(16),
    marginBottom: scale(20),
    gap: scale(6),
  },
  categoryPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scale(8),
    paddingHorizontal: scale(2),
    borderRadius: scale(20),
  },
  dot: {
    width: scale(6),
    height: scale(6),
    borderRadius: scale(3),
    marginRight: scale(4),
  },
  categoryPillText: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Medium',
  },
  mustWatchCard: {
    backgroundColor: '#F4FBD6',
    borderRadius: scale(16),
    marginHorizontal: scale(16),
    marginBottom: scale(20),
    padding: scale(16),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1.5,
    borderColor: '#94C23C',
    borderStyle: 'dashed',
  },
  mustWatchLeft: {
    flex: 1,
    marginRight: scale(12),
  },
  mustWatchBadge: {
    backgroundColor: '#1C1F2A',
    borderRadius: scale(10),
    paddingHorizontal: scale(8),
    paddingVertical: scale(2),
    alignSelf: 'flex-start',
    marginBottom: scale(8),
  },
  mustWatchBadgeText: {
    color: colors.white,
    fontSize: scale(9),
    fontWeight: 'bold',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  mustWatchTitle: {
    fontSize: scale(16),
    fontWeight: 'bold',
    color: '#94C23C',
    marginBottom: scale(4),
    fontFamily: 'BricolageGrotesque-Bold',
  },
  mustWatchSubtitle: {
    fontSize: scale(11),
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  mustWatchRight: {
    alignItems: 'center',
  },
  mustWatchPlayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1C1F2A',
    paddingHorizontal: scale(10),
    paddingVertical: scale(6),
    borderRadius: scale(12),
    marginBottom: scale(6),
  },
  mustWatchPlayBtnText: {
    color: colors.white,
    fontSize: scale(10),
    fontWeight: 'bold',
    marginLeft: scale(4),
    fontFamily: 'BricolageGrotesque-Bold',
  },
  mustWatchTipTime: {
    fontSize: scale(9),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  videoListContainer: {
    paddingHorizontal: scale(16),
  },
  videoCard: {
    flexDirection: 'row',
    backgroundColor: colors.white,
    borderRadius: scale(16),
    padding: scale(12),
    marginBottom: scale(16),
    borderWidth: 1,
    borderColor: '#EAECEF',
  },
  thumbnailContainer: {
    width: scale(110),
    height: scale(72),
    borderRadius: scale(10),
    overflow: 'hidden',
    position: 'relative',
  },
  thumbnail: {
    width: '100%',
    height: '100%',
  },
  playBadge: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: scale(-18),
    marginTop: scale(-18),
    width: scale(36),
    height: scale(36),
    borderRadius: scale(18),
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardInfo: {
    flex: 1,
    marginLeft: scale(12),
    justifyContent: 'center',
  },
  categoryLabel: {
    fontSize: scale(10),
    fontWeight: 'bold',
    marginBottom: scale(2),
    fontFamily: 'BricolageGrotesque-Bold',
  },
  videoTitle: {
    fontSize: scale(13),
    fontWeight: 'bold',
    color: '#1C1F2A',
    marginBottom: scale(4),
    fontFamily: 'BricolageGrotesque-Bold',
  },
  metaText: {
    fontSize: scale(11),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  stateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scale(48),
    paddingHorizontal: scale(24),
  },
  stateText: {
    marginTop: scale(12),
    fontSize: scale(13),
    color: '#8E8E93',
    textAlign: 'center',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  errorText: {
    fontSize: scale(13),
    color: '#EF4444',
    textAlign: 'center',
    marginBottom: scale(16),
    fontFamily: 'BricolageGrotesque-Regular',
  },
  retryButton: {
    paddingVertical: scale(10),
    paddingHorizontal: scale(24),
    borderRadius: scale(20),
    backgroundColor: '#1C1F2A',
  },
  retryButtonText: {
    color: colors.white,
    fontSize: scale(13),
    fontWeight: 'bold',
    fontFamily: 'BricolageGrotesque-SemiBold',
  },
  subscriptionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: scale(16),
    marginTop: scale(16),
    paddingVertical: scale(10),
    paddingHorizontal: scale(12),
    backgroundColor: '#FEF3C7',
    borderRadius: scale(10),
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  subscriptionBannerText: {
    flex: 1,
    fontSize: scale(11),
    color: '#92400E',
    fontFamily: 'BricolageGrotesque-Regular',
    marginRight: scale(10),
  },
  subscriptionBannerCta: {
    backgroundColor: '#1C1F2A',
    paddingHorizontal: scale(12),
    paddingVertical: scale(6),
    borderRadius: scale(10),
  },
  subscriptionBannerCtaText: {
    color: colors.white,
    fontSize: scale(11),
    fontWeight: 'bold',
    fontFamily: 'BricolageGrotesque-SemiBold',
  },
});
