import { StyleSheet } from 'react-native';
import { scale } from './scale';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FC',
  },
  scrollContent: {
    paddingHorizontal: scale(16),
    paddingTop: scale(24),
  },

  heroSection: {
    alignItems: 'center',
    marginBottom: scale(24),
  },
  pulseContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: scale(160),
    height: scale(160),
    marginBottom: scale(16),
  },
  pulseRing: {
    position: 'absolute',
    backgroundColor: '#94C23C',
  },
  micCircle: {
    width: scale(72),
    height: scale(72),
    borderRadius: scale(36),
    backgroundColor: '#F0F9E8',
    borderWidth: 2,
    borderColor: '#94C23C',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#94C23C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  micCircleActive: {
    backgroundColor: '#94C23C',
    borderColor: '#78A832',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: scale(20),
    paddingHorizontal: scale(14),
    paddingVertical: scale(6),
    gap: scale(6),
  },
  statusBadgeSuccess: {
    backgroundColor: '#DCFCE7',
  },
  statusBadgeFail: {
    backgroundColor: '#FEE2E2',
  },
  statusBadgeTesting: {
    backgroundColor: '#FEF3C7',
  },
  statusDot: {
    width: scale(8),
    height: scale(8),
    borderRadius: scale(4),
    backgroundColor: '#94C23C',
  },
  statusText: {
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-SemiBold',
    color: '#1A2151',
    fontWeight: '600',
  },

  waveformCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: scale(16),
    padding: scale(16),
    marginBottom: scale(16),
    borderWidth: 1,
    borderColor: '#EAECEF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  waveformLabel: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Bold',
    color: '#8E8E93',
    fontWeight: 'bold',
    marginBottom: scale(12),
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  waveformRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: scale(56),
    marginBottom: scale(12),
  },
  waveBar: {
    width: scale(6),
    borderRadius: scale(3),
    minHeight: scale(4),
  },
  dbRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  dbLabel: {
    fontSize: scale(11),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
    minWidth: scale(60),
  },
  volumeTrack: {
    flex: 1,
    height: scale(6),
    backgroundColor: '#F2F2F7',
    borderRadius: scale(3),
    overflow: 'hidden',
  },
  volumeFill: {
    height: '100%',
    borderRadius: scale(3),
  },
  dbValue: {
    fontSize: scale(11),
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-SemiBold',
    fontWeight: '600',
    minWidth: scale(42),
    textAlign: 'right',
  },

  tipsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: scale(16),
    padding: scale(16),
    marginBottom: scale(16),
    borderWidth: 1,
    borderColor: '#EAECEF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  tipsTitle: {
    fontSize: scale(14),
    fontFamily: 'BricolageGrotesque-Bold',
    color: '#1A2151',
    fontWeight: 'bold',
    marginBottom: scale(12),
  },
  tipRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: scale(8),
    gap: scale(10),
  },
  tipIcon: {
    fontSize: scale(16),
    lineHeight: scale(22),
  },
  tipText: {
    flex: 1,
    fontSize: scale(13),
    color: '#4B5563',
    fontFamily: 'BricolageGrotesque-Regular',
    lineHeight: scale(20),
  },

  stepsContainer: {
    marginBottom: scale(20),
  },
  stepsTitle: {
    fontSize: scale(14),
    fontFamily: 'BricolageGrotesque-Bold',
    color: '#1A2151',
    fontWeight: 'bold',
    marginBottom: scale(12),
  },
  stepCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: scale(12),
    padding: scale(14),
    marginBottom: scale(8),
    borderWidth: 1,
    borderColor: '#EAECEF',
    gap: scale(12),
  },
  stepCardActive: {
    borderColor: '#94C23C',
    backgroundColor: '#F7FEF0',
  },
  stepNumber: {
    width: scale(28),
    height: scale(28),
    borderRadius: scale(14),
    backgroundColor: '#F2F2F7',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  stepNumberDone: {
    backgroundColor: '#94C23C',
  },
  stepNumberActive: {
    backgroundColor: '#1A2151',
  },
  stepNumberText: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Bold',
    color: '#8E8E93',
    fontWeight: 'bold',
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-SemiBold',
    color: '#8E8E93',
    fontWeight: '600',
    marginBottom: scale(2),
  },
  stepDescription: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Regular',
    color: '#9CA3AF',
    lineHeight: scale(18),
  },

  actionsContainer: {
    marginTop: scale(4),
  },
  completeActions: {
    gap: scale(10),
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A2151',
    borderRadius: scale(14),
    paddingVertical: scale(15),
    gap: scale(8),
    shadowColor: '#1A2151',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  stopBtn: {
    backgroundColor: '#F59E0B',
    shadowColor: '#F59E0B',
  },
  successBtn: {
    backgroundColor: '#94C23C',
    shadowColor: '#94C23C',
  },
  dangerBtn: {
    backgroundColor: '#EF4444',
    shadowColor: '#EF4444',
  },
  primaryBtnText: {
    fontSize: scale(15),
    fontFamily: 'BricolageGrotesque-Bold',
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  secondaryBtn: {
    alignItems: 'center',
    paddingVertical: scale(12),
    borderRadius: scale(14),
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  secondaryBtnText: {
    fontSize: scale(14),
    fontFamily: 'BricolageGrotesque-SemiBold',
    color: '#6B7280',
    fontWeight: '600',
  },
  disabledBtn: {
    opacity: 0.6,
  },
});
