import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';
import { scale } from './scale';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F7',
  },
  content: {
    flex: 1,
    paddingHorizontal: scale(16),
    paddingTop: scale(16),
  },
  // ── Dropdown ──
  dropdownButton: {
    backgroundColor: colors.white,
    borderRadius: scale(12),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    paddingVertical: scale(12),
    paddingHorizontal: scale(16),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: scale(12),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  dropdownText: {
    fontSize: scale(14),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#1C1F2A',
  },
  // ── Tab Bar ──
  tabBarContainer: {
    flexDirection: 'row',
    backgroundColor: '#EFEFEF',
    borderRadius: scale(10),
    padding: scale(3),
    marginBottom: scale(12),
  },
  tabItem: {
    flex: 1,
    paddingVertical: scale(8),
    borderRadius: scale(8),
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabItemActive: {
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
  },
  tabTextActive: {
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-SemiBold',
  },
  // ── Search ──
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scale(12),
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: scale(10),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    paddingHorizontal: scale(12),
    height: scale(44),
  },
  searchIconWrapper: {
    marginRight: scale(8),
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchInput: {
    flex: 1,
    fontSize: scale(14),
    fontFamily: 'BricolageGrotesque-Regular',
    color: '#1C1F2A',
    height: '100%',
    padding: 0,
  },
  filterButton: {
    width: scale(44),
    height: scale(44),
    backgroundColor: '#94C23C',
    borderRadius: scale(10),
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: scale(8),
  },
  // ── List ──
  scrollView: { flex: 1 },
  listContainer: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: scale(16),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
  },
  listContent: { flexGrow: 1 },
  footerLoader: {
    paddingVertical: scale(16),
    alignItems: 'center',
    justifyContent: 'center',
  },
  questionsCardContainer: {
    backgroundColor: colors.white,
    borderRadius: scale(16),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    paddingHorizontal: scale(16),
  },
  questionsCardWrapper: {
    backgroundColor: colors.white,
    paddingHorizontal: scale(16),
  },
  questionItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: scale(16),
  },
  questionLeft: {
    flex: 1,
    marginRight: scale(12),
  },
  questionTitle: {
    fontSize: scale(14),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#1C1F2A',
    marginBottom: scale(8),
    lineHeight: scale(20),
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
    flexWrap: 'wrap',
  },
  idBadge: {
    backgroundColor: '#E5E5EA',
    borderRadius: scale(6),
    paddingHorizontal: scale(8),
    paddingVertical: scale(2),
  },
  idBadgeText: {
    fontSize: scale(9),
    fontFamily: 'BricolageGrotesque-Bold',
    color: '#1C1C1E',
    fontWeight: 'bold',
  },
  newBadge: {
    backgroundColor: '#1A2151',
    borderRadius: scale(10),
    paddingHorizontal: scale(8),
    paddingVertical: scale(2),
  },
  newBadgeText: {
    color: colors.white,
    fontSize: scale(9),
    fontWeight: 'bold',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  diffBadge: {
    borderRadius: scale(6),
    paddingHorizontal: scale(8),
    paddingVertical: scale(2),
  },
  diffBadgeText: {
    fontSize: scale(9),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
  },
  tagWrapper: { padding: scale(2) },
  viewButton: {
    borderWidth: 1,
    borderColor: '#94C23C',
    borderRadius: scale(10),
    paddingVertical: scale(6),
    paddingHorizontal: scale(12),
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(4),
  },
  viewButtonText: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#1C1F2A',
  },
  separator: {
    height: 1,
    backgroundColor: '#F2F2F7',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scale(60),
  },
  emptyText: {
    fontSize: scale(14),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
  },
  // ── Modal ──
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: scale(24),
  },
  modalContent: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: scale(16),
    padding: scale(20),
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  modalTitle: {
    fontSize: scale(16),
    fontFamily: 'BricolageGrotesque-Bold',
    color: '#1C1F2A',
    fontWeight: 'bold',
    marginBottom: scale(16),
    textAlign: 'center',
  },
  modalScroll: { width: '100%' },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: scale(12),
    paddingHorizontal: scale(16),
    borderRadius: scale(8),
    marginBottom: scale(4),
  },
  modalItemSelected: {
    backgroundColor: '#F2F2F7',
  },
  modalItemText: {
    fontSize: scale(14),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#333333',
  },
  modalItemTextSelected: {
    color: colors.primary,
    fontWeight: '700',
  },
  // ── Tag Colour Picker (modal) ──
  tagPickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: scale(24),
  },
  tagPickerCard: {
    width: '100%',
    maxWidth: scale(320),
    backgroundColor: colors.white,
    borderRadius: scale(14),
    paddingVertical: scale(8),
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 6,
  },
  tagPickerTitle: {
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-SemiBold',
    color: '#1C1F2A',
    paddingHorizontal: scale(14),
    paddingTop: scale(8),
    paddingBottom: scale(10),
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F7',
  },
  tagPickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: scale(12),
    paddingHorizontal: scale(14),
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F7',
    gap: scale(10),
  },
  tagPickerItemLast: {
    borderBottomWidth: 0,
  },
  tagPickerItemActive: {
    backgroundColor: '#F8F9FA',
  },
  tagPickerDot: {
    width: scale(16),
    height: scale(16),
    borderRadius: scale(8),
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  tagPickerItemText: {
    flex: 1,
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#1C1F2A',
  },
  tagPickerItemTextActive: {
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#007AFF',
  },
  tagPickerCheck: {
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#007AFF',
  },
  tagPickerRemoveItem: {
    paddingVertical: scale(12),
    paddingHorizontal: scale(14),
    alignItems: 'center',
    backgroundColor: '#FFF5F5',
    borderTopWidth: 1,
    borderTopColor: '#F2F2F7',
  },
  tagPickerRemoveText: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#FF3B30',
  },
});
