import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';
import { scale } from './scale';

// All styles for the PracticeQuestionDetail screen + its sub-components.
// The 17 audio-display style entries that were left behind when MediaConsole
// was extracted (audioDisplayContainer / audioIconBadge / playbackProgressRow
// / progressTime* / progressBar* / questionAudioPlayBtn / speedSelector* /
// speedDropdown / speedItem* / statusSectionDivider) have been removed.
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F7',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: scale(14),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
    marginTop: scale(12),
  },
  contentScroll: {
    flex: 1,
  },
  contentContainer: {
    padding: scale(16),
    paddingBottom: scale(100),
  },
  headerRightBtn: {
    padding: scale(8),
    marginRight: scale(4),
  },
  // Tag colour picker dropdown
  tagPickerBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 49,
  },
  tagPickerDropdown: {
    position: 'absolute',
    top: scale(56),
    right: scale(12),
    backgroundColor: colors.white,
    borderRadius: scale(10),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 50,
    minWidth: scale(160),
    overflow: 'hidden',
  },
  tagPickerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: scale(10),
    paddingHorizontal: scale(12),
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F7',
    gap: scale(10),
  },
  tagPickerItemLast: {
    borderBottomWidth: 0,
  },
  tagPickerItemActive: {
    backgroundColor: '#F8F9FA',
  },
  tagPickerDot: {
    width: scale(14),
    height: scale(14),
    borderRadius: scale(7),
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  tagPickerItemText: {
    flex: 1,
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#1C1F2A',
  },
  tagPickerItemTextActive: {
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#007AFF',
  },
  tagPickerCheck: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#007AFF',
  },
  tagPickerRemoveItem: {
    paddingVertical: scale(10),
    paddingHorizontal: scale(12),
    alignItems: 'center',
    backgroundColor: '#FFF5F5',
    borderTopWidth: 1,
    borderTopColor: '#F2F2F7',
  },
  tagPickerRemoveText: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#FF3B30',
  },
  // Lavender Instruction Banner
  lavenderInstructionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F3FF',
    borderRadius: scale(10),
    padding: scale(12),
    marginBottom: scale(16),
    gap: scale(8),
  },
  lavenderInstructionText: {
    flex: 1,
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#5C527F',
    lineHeight: scale(16),
  },
  // Question metadata block (title + chips)
  metaBlock: {
    marginBottom: scale(16),
  },
  metaTitle: {
    fontSize: scale(15),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#1C1F2A',
    marginBottom: scale(8),
    lineHeight: scale(20),
  },
  metaChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: scale(6),
  },
  metaIdChip: {
    backgroundColor: '#F2F2F7',
    borderRadius: scale(6),
    paddingHorizontal: scale(8),
    paddingVertical: scale(3),
  },
  metaIdChipText: {
    fontSize: scale(10),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#48484A',
  },
  metaDiffChip: {
    borderRadius: scale(6),
    paddingHorizontal: scale(8),
    paddingVertical: scale(3),
  },
  metaDiffChipText: {
    fontSize: scale(10),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    letterSpacing: 0.3,
  },
  metaNewChip: {
    backgroundColor: '#FFF1E5',
    borderRadius: scale(6),
    paddingHorizontal: scale(8),
    paddingVertical: scale(3),
  },
  metaNewChipText: {
    fontSize: scale(10),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#FF9500',
  },
  metaAttemptChip: {
    backgroundColor: '#E5F1FF',
    borderRadius: scale(6),
    paddingHorizontal: scale(8),
    paddingVertical: scale(3),
  },
  metaAttemptChipText: {
    fontSize: scale(10),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#007AFF',
  },
  // Mode Switcher (Read Aloud Capsule Switch)
  modeSwitcherContainer: {
    flexDirection: 'row',
    backgroundColor: '#E5E5EA',
    borderRadius: scale(20),
    padding: scale(2),
    marginBottom: scale(16),
  },
  modeSwitcherTab: {
    flex: 1,
    paddingVertical: scale(8),
    alignItems: 'center',
    borderRadius: scale(18),
  },
  modeSwitcherTabActive: {
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  modeSwitcherText: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
  },
  modeSwitcherTextActive: {
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
  },
  // Question Panel Card
  questionPanelCard: {
    backgroundColor: colors.white,
    borderRadius: scale(16),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    padding: scale(16),
    marginBottom: scale(16),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
  },
  imageWrapper: {
    width: '100%',
    height: scale(180),
    backgroundColor: '#F8F9FA',
    borderRadius: scale(10),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: scale(12),
    borderWidth: 1,
    borderColor: '#F2F2F7',
  },
  questionImage: {
    width: '100%',
    height: '100%',
  },
  situationContainer: {
    backgroundColor: '#F8F9FA',
    borderRadius: scale(10),
    padding: scale(12),
    marginBottom: scale(12),
    borderWidth: 1,
    borderColor: '#E5E5EA',
  },
  situationHeader: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#1C1F2A',
    marginBottom: scale(4),
  },
  situationText: {
    fontSize: scale(14),
    fontFamily: 'BricolageGrotesque-Regular',
    color: '#48484A',
    lineHeight: scale(20),
  },
  paragraphText: {
    fontSize: scale(15),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#1C1F2A',
    lineHeight: scale(24),
  },
  // Outline buttons for translation/transcript/sample
  cardActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    gap: scale(8),
    marginTop: scale(12),
    zIndex: 1,
  },
  outlineBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#8E8E93',
    borderRadius: scale(8),
    minHeight: scale(52),
    paddingVertical: scale(8),
    paddingHorizontal: scale(6),
    gap: scale(3),
    overflow: 'hidden',
  },
  outlineBtnActive: {
    backgroundColor: '#8E8E93',
  },
  outlineBtnText: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#8E8E93',
  },
  outlineBtnTextSingleLine: {
    flexShrink: 1,
    textAlign: 'center',
  },
  outlineBtnTextTwoLine: {
    textAlign: 'center',
    lineHeight: scale(14),
  },
  outlineBtnTextActive: {
    color: colors.white,
  },
  outlineBtnBlue: {
    borderColor: '#007AFF',
  },
  outlineBtnBlueActive: {
    backgroundColor: '#007AFF',
  },
  outlineBtnTextBlue: {
    color: '#007AFF',
  },
  outlineBtnPurple: {
    borderColor: '#7C3AED',
  },
  outlineBtnPurpleActive: {
    backgroundColor: '#7C3AED',
  },
  outlineBtnTextPurple: {
    color: '#7C3AED',
  },
  // Expandable Panels
  inlineExpandPanel: {
    width: '100%',
    backgroundColor: '#F8F9FA',
    borderRadius: scale(10),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    padding: scale(12),
    marginTop: scale(12),
  },
  expandPanelTitle: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#1C1F2A',
    marginBottom: scale(6),
  },
  expandPanelText: {
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-Regular',
    color: '#48484A',
    lineHeight: scale(18),
  },
  langSelectorRowInline: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scale(8),
    zIndex: 15,
  },
  langLabelInline: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#1C1C1E',
    marginRight: scale(6),
  },
  langPickerContainerInline: {
    zIndex: 15,
  },
  langPickerBtnInline: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F2F7',
    borderRadius: scale(6),
    paddingVertical: scale(4),
    paddingHorizontal: scale(8),
    gap: scale(4),
  },
  langPickerTextInline: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#1C1C1E',
  },
  langDropdownInline: {
    position: 'absolute',
    top: scale(24),
    left: 0,
    backgroundColor: colors.white,
    borderRadius: scale(6),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    width: scale(90),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    zIndex: 20,
  },
  langItemInline: {
    paddingVertical: scale(6),
    paddingHorizontal: scale(10),
  },
  langItemTextInline: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Regular',
    color: '#1C1C1E',
  },
  sampleAudioContainerInline: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: scale(12),
    gap: scale(8),
  },
  samplePlayBtnInline: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7C3AED',
    borderRadius: scale(6),
    paddingVertical: scale(6),
    paddingHorizontal: scale(12),
    gap: scale(4),
  },
  samplePlayBtnTextInline: {
    color: colors.white,
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
  },
  sampleTimerTextInline: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
  },
  // Card Footer
  cardFooterDivider: {
    height: 1,
    backgroundColor: '#E5E5EA',
    marginVertical: scale(12),
    width: '100%',
  },
  cardFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  attemptCountText: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#8E8E93',
  },
  reportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E5EA',
    borderRadius: scale(6),
    paddingVertical: scale(6),
    paddingHorizontal: scale(10),
    gap: scale(6),
    backgroundColor: '#FFFFFF',
  },
  reportBtnText: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
  },
  // Logs / History Section
  logsSection: {
    backgroundColor: colors.white,
    borderRadius: scale(16),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    padding: scale(16),
    marginBottom: scale(16),
  },
  logsTabSwitcher: {
    flexDirection: 'row',
    backgroundColor: '#F2F2F7',
    borderRadius: scale(10),
    padding: scale(2),
    marginBottom: scale(12),
  },
  logsTabBtn: {
    flex: 1,
    paddingVertical: scale(6),
    alignItems: 'center',
    borderRadius: scale(8),
  },
  logsTabBtnActive: {
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  logsTabText: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
  },
  logsTabTextActive: {
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
  },
  filterWrapper: {
    marginBottom: scale(12),
    zIndex: 10,
  },
  filterDropdownHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#E5E5EA',
    borderRadius: scale(8),
    paddingVertical: scale(8),
    paddingHorizontal: scale(12),
    backgroundColor: '#F8F9FA',
  },
  filterDropdownLabel: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
  },
  filterDropdownValue: {
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#1C1F2A',
  },
  filterDropdownList: {
    position: 'absolute',
    top: scale(36),
    left: 0,
    right: 0,
    backgroundColor: colors.white,
    borderRadius: scale(8),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
    zIndex: 15,
  },
  filterDropdownItem: {
    paddingVertical: scale(10),
    paddingHorizontal: scale(12),
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F7',
  },
  filterDropdownItemActive: {
    backgroundColor: '#F2F2F7',
  },
  filterDropdownItemText: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Regular',
    color: '#48484A',
  },
  filterDropdownItemTextActive: {
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#007AFF',
  },
  attemptLogItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: scale(8),
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F7',
  },
  attemptLogItemMain: {
    flex: 1,
    paddingRight: scale(8),
  },
  attemptDate: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#48484A',
    marginBottom: scale(2),
  },
  attemptSubscores: {
    fontSize: scale(9),
    fontFamily: 'BricolageGrotesque-Regular',
    color: '#8E8E93',
  },
  // Right-side cluster wrapping the inline play button + score badge.
  // Tight `gap` keeps the two visual elements grouped so the row reads
  // as `[date / subscores ........] [play | score]` rather than three
  // scattered children.
  attemptRightCluster: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
  },
  attemptPlayBtn: {
    width: scale(22),
    height: scale(22),
    borderRadius: scale(11),
    backgroundColor: '#007AFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  attemptPlayBtnActive: {
    backgroundColor: '#FF3B30',
  },
  hiddenAttemptVideoContainer: {
    position: 'absolute',
    top: -1000,
    left: -1000,
    width: 1,
    height: 1,
    overflow: 'hidden',
    opacity: 0,
  },
  hiddenAttemptVideo: {
    width: 1,
    height: 1,
    backgroundColor: 'transparent',
    opacity: 0,
  },
  attemptScoreBadge: {
    borderRadius: scale(6),
    width: scale(32),
    paddingVertical: scale(3),
    alignItems: 'center',
    justifyContent: 'center',
  },
  attemptScoreBadgeText: {
    color: colors.white,
    fontSize: scale(10),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
  },
  noAttemptsText: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
    textAlign: 'center',
    paddingVertical: scale(12),
  },
  // Navigation Footer
  navigationFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: scale(64),
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: '#E5E5EA',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: scale(16),
  },
  navFooterOutlineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E5EA',
    borderRadius: scale(20),
    paddingVertical: scale(8),
    paddingHorizontal: scale(16),
    gap: scale(4),
    backgroundColor: colors.white,
  },
  navFooterOutlineBtnDisabled: {
    opacity: 0.3,
  },
  navFooterOutlineText: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#48484A',
  },
  navFooterOutlineTextDisabled: {
    color: '#8E8E93',
  },
  navFooterSubmitBtn: {
    backgroundColor: '#94C23C',
    borderRadius: scale(20),
    paddingVertical: scale(8),
    paddingHorizontal: scale(24),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#94C23C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  navFooterSubmitBtnDisabled: {
    backgroundColor: '#C5C5C7',
    shadowOpacity: 0,
    elevation: 0,
  },
  navFooterSubmitBtnSubmitted: {
    backgroundColor: '#94C23C',
  },
  navFooterSubmitContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
  },
  navFooterSubmitText: {
    color: colors.white,
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
  },
  // Modal overlay
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: scale(20),
    borderTopRightRadius: scale(20),
    height: '85%',
    padding: scale(16),
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F7',
    paddingBottom: scale(12),
    marginBottom: scale(16),
  },
  modalHeaderTitleBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  modalHeaderIconContainer: {
    backgroundColor: '#F0EBF8',
    padding: scale(6),
    borderRadius: scale(8),
  },
  modalTitleText: {
    fontSize: scale(16),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#1C1F2A',
  },
  modalSubtitleText: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
    marginTop: scale(2),
  },
  modalCloseIconBtn: {
    padding: scale(4),
  },
  modalScrollContent: {
    flex: 1,
  },
  topScoreInfoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: scale(16),
    borderWidth: 1,
    borderColor: '#EAECEF',
    padding: scale(16),
    marginBottom: scale(16),
    gap: scale(16),
  },
  topLeftProgressColumn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topRightBreakdownColumn: {
    flex: 1.3,
    gap: scale(8),
  },
  topBreakdownRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topBreakdownLabelGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  topBreakdownLabel: {
    fontFamily: 'BricolageGrotesque-Medium',
    fontSize: scale(12),
    color: '#48484A',
  },
  topBreakdownValue: {
    fontFamily: 'BricolageGrotesque-Bold',
    fontSize: scale(12),
    color: '#1C1F2A',
    fontWeight: 'bold',
  },
  analyticsSection: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EAECEF',
    borderRadius: scale(16),
    padding: scale(16),
    marginBottom: scale(16),
  },
  analyticsTitle: {
    fontFamily: 'BricolageGrotesque-Bold',
    fontSize: scale(12),
    color: '#7C3AED',
    fontWeight: 'bold',
    marginBottom: scale(8),
    letterSpacing: 0.5,
  },
  analyticsBody: {
    fontFamily: 'BricolageGrotesque-Regular',
    fontSize: scale(12),
    color: '#48484A',
    lineHeight: scale(18),
  },
  wordHighlightCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: scale(16),
    borderWidth: 1,
    borderColor: '#EAECEF',
    padding: scale(16),
    marginBottom: scale(16),
  },
  wordsListWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: scale(6),
    marginBottom: scale(12),
  },
  wordText: {
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-Medium',
    lineHeight: scale(18),
  },
  colorGuideRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(16),
    borderTopWidth: 1,
    borderTopColor: '#F2F2F7',
    paddingTop: scale(12),
  },
  guideItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(6),
  },
  guideDot: {
    width: scale(8),
    height: scale(8),
    borderRadius: scale(4),
  },
  guideText: {
    fontSize: scale(10),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
  },
  detailRemarkCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EAECEF',
    borderRadius: scale(16),
    padding: scale(16),
    marginBottom: scale(12),
  },
  detailRemarkHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailIconBox: {
    width: scale(32),
    height: scale(32),
    borderRadius: scale(8),
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailRemarkTitleGroup: {
    flex: 1,
    marginHorizontal: scale(10),
  },
  detailRemarkTitle: {
    fontFamily: 'BricolageGrotesque-Bold',
    fontSize: scale(13),
    color: '#1C1F2A',
    fontWeight: 'bold',
  },
  detailRemarkDesc: {
    fontFamily: 'BricolageGrotesque-Regular',
    fontSize: scale(10),
    color: '#8E8E93',
  },
  detailRemarkScore: {
    fontFamily: 'BricolageGrotesque-Bold',
    fontSize: scale(13),
    color: '#1C1F2A',
    fontWeight: 'bold',
  },
  detailRemarkDivider: {
    height: 1,
    backgroundColor: '#F2F2F7',
    marginVertical: scale(12),
  },
  detailRemarkBullets: {
    gap: scale(8),
  },
  detailBulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: scale(6),
  },
  detailBulletDot: {
    width: scale(6),
    height: scale(6),
    borderRadius: scale(3),
    marginTop: scale(6),
    marginRight: scale(8),
  },
  detailBulletText: {
    flex: 1,
    fontFamily: 'BricolageGrotesque-Regular',
    fontSize: scale(11.5),
    color: '#48484A',
    lineHeight: scale(16),
  },
  closeOverlayBtn: {
    backgroundColor: '#111827',
    borderRadius: scale(12),
    paddingVertical: scale(14),
    alignItems: 'center',
    marginTop: scale(12),
  },
  closeOverlayBtnText: {
    color: colors.white,
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
  },
  reportModalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: scale(20),
    borderTopRightRadius: scale(20),
    height: '70%',
    padding: scale(16),
  },
  reportHeaderIconContainer: {
    backgroundColor: '#FFF0F0',
    padding: scale(6),
    borderRadius: scale(8),
  },
  reportSectionHeading: {
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#1C1F2A',
    marginTop: scale(16),
    marginBottom: scale(12),
  },
  reasonsPillContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: scale(8),
    marginBottom: scale(12),
  },
  reasonPill: {
    borderWidth: 1,
    borderColor: '#E5E5EA',
    borderRadius: scale(8),
    paddingVertical: scale(8),
    paddingHorizontal: scale(12),
    backgroundColor: '#FFFFFF',
  },
  reasonPillActive: {
    borderColor: '#94C23C',
    backgroundColor: '#F5FBEA',
  },
  reasonPillText: {
    fontFamily: 'BricolageGrotesque-Medium',
    fontSize: scale(11.5),
    color: '#48484A',
  },
  reasonPillTextActive: {
    color: '#94C23C',
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
  },
  detailsInput: {
    borderWidth: 1,
    borderColor: '#E5E5EA',
    borderRadius: scale(10),
    padding: scale(12),
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Regular',
    height: scale(90),
    color: '#1C1F2A',
    backgroundColor: '#FAFAFA',
    marginBottom: scale(20),
  },
  submitReportBtn: {
    backgroundColor: '#94C23C',
    borderRadius: scale(12),
    paddingVertical: scale(14),
    alignItems: 'center',
    shadowColor: '#94C23C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: scale(16),
  },
  submitReportBtnDisabled: {
    backgroundColor: '#C5C5C7',
    shadowOpacity: 0,
    elevation: 0,
  },
  submitReportBtnText: {
    color: colors.white,
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
  },
  consolePlaceholder: {
    padding: scale(16),
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: scale(12),
    width: '100%',
  },
  placeholderText: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
    marginTop: scale(6),
  },
  loadMoreAttemptsBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: scale(10),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E5EA',
    borderRadius: scale(8),
    marginTop: scale(10),
    marginBottom: scale(20),
  },
  loadMoreAttemptsText: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#007AFF',
  },
  writingContainer: {
    width: '100%',
    marginVertical: scale(10),
  },
  writingTextInput: {
    borderWidth: 1,
    borderColor: '#E5E5EA',
    borderRadius: scale(12),
    padding: scale(12),
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-Regular',
    minHeight: scale(150),
    maxHeight: scale(250),
    color: '#1C1F2A',
    backgroundColor: '#FAFAFA',
    textAlignVertical: 'top',
  },
  wordCountText: {
    fontSize: scale(11),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#8E8E93',
    marginTop: scale(8),
    textAlign: 'right',
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: scale(8),
    gap: scale(4),
  },
  timerLabel: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Medium',
    color: '#8E8E93',
  },
  timerValue: {
    fontSize: scale(12),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#FF9500', // Orange color for urgency
  },
  fixedWritingContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E5E5EA',
    paddingHorizontal: scale(16),
    paddingTop: scale(8),
    paddingBottom: scale(12),
    zIndex: 5,
  },
  timerAndWordCountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: scale(6),
  },
  fixedTimerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  fixedWordCountText: {
    fontSize: scale(11.5),
    fontFamily: 'BricolageGrotesque-Bold',
    fontWeight: 'bold',
    color: '#8E8E93',
  },
  fixedWritingTextInput: {
    borderWidth: 1,
    borderColor: '#E5E5EA',
    borderRadius: scale(10),
    padding: scale(10),
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-Regular',
    minHeight: scale(45),
    maxHeight: scale(150),
    color: '#1C1F2A',
    backgroundColor: '#FAFAFA',
    textAlignVertical: 'top',
  },
});
