import { BASE_URL } from "./Config";

const URLS: Record<string, string> = {
  // Common Keys
  REQUEST_OTP: "requestotp",
  PAYMENT_STATUS: "process/in-app/payment",
  VERIFY_IOS_IAP: "process/ios/in-app/payment",
  MOCK_TEST_LIST: "web/mock1?new_format=0",
  MOCK_TEST_DETAIL: "question/detail",
  EXTENSIVE_MOCK_TEST_LIST: "web/mock1?new_format=1",
  PENDING_TEST_LIST: "pending/mock?new_format=0",
  EXTENSIVE_PENDING_TEST_LIST: "pending/mock?new_format=1",
  SIGN_IN: "login",
  LOGOUT: "logout",
  SIGN_UP: "app/signup",
  SEND_SIGN_UP: "app/send/otp",
  VERIFY_EMAIL_PHONE: "user-validation",
  FORGOTPASSWORD: "forgot",
  RESET_FORGOTPASSWORD: "reset-password",
  DEVICE_TOKEN: "deviceToken",
  DEVICE_TOKEN_USER: "deviceToken/user",
  GOOGLE_SOCIAL_LOGIN: "googleSignUp",
  APPLE_SOCIAL_LOGIN: "appleSignUp",
  GOOGLE_LOGIN: "googleSignUp",
  APPLE_LOGIN: "appleSignUp",
  PREDICTION_COUNT: "/prediction/count",

  // User Profile
  USER_PROFILE: "user-my-profile",
  USER_PROFILE_DELETE: "user/delete",
  USER_PROFILE_UPDATE: "saveUser",
  CONTACT_US: "post/contact",
  CONTACT_DETAILS: "contact-details",

  // Dashboard
  DASHBOARD_DATA: "get_dashboard_data",
  PTE_CORE_DASHBOARD_DATA: "get_dashboard_data",

  MARK_N_VIDEO_WATCHED: "mark/viewed",
  UPDATE_EXAM_DATE: "updateTarget",
  BOOK_TRAIL_CLASSES: "btc-submit-data",
  SUBMIT_QUERY: "submit-query",
  GET_ALL_BRANCHES: "getAllBranches",

  // Practice
  LIST_QUESTION: "question",
  SPEAKING_READ_ALOUD: "question/1",
  SPEAKING_REPEAT_SENTENCE: "question/2",
  SPEAKING_DESCRIBE_IMAGE: "question/3",
  SPEAKING_RETELL_LECTURE: "question/4",
  SPEAKING_ANSWER_SHORT_QUESTION: "question/5",
  WRITING_SUMMERISE_TEXT: "question/6",
  WRITING_ESSAY: "question/7",
  READING_MULTIPLE_SINGLE_ANSWER: "question/8",
  READING_MULTIPLE_MULTIPLE_ANSWER: "question/9",
  READING_REORDER_PARAGRAPH: "question/10",
  READING_FILL_BLANK: "question/11",
  READING_WRITING_FILL_BLANK: "question/12",
  LISTENING_SUMMARISE_SPOKEN_TEXT: "question/13",
  LISTENING_MCQ_SINGLE_ANSWER: "question14",
  LISTENING_MCQ_MULTIPLE_ANSWER: "question/15",
  LISTENING_FILL_BLANK: "question/16",
  LISTENING_HIGHLIGHTING_SUMMARIES: "question/17",
  LISTENING_MISSING_WORDS: "question/18",
  LISTENING_INCORRECT_WORDS: "question/19",
  LISTENING_FROM_DICTATION: "question/20",

  EXAM_QUESTIONS: "question/1?type=3",
  MONTHLY_PREDICTION: "question/1?type=2",

  SUBMIT_ANSWER: "check/answer2",
  PTE_CORE_SUBMIT_ANSWER: "submit/practice",

  SUBMIT_EXPLANATION: "submit-explanation",
  SET_TAG: "set/tag",

  SUBMIT_MOCK: "submit/mock",
  REMAINING_MOCK: "set/mockTime",
  SUBMIT_FAILED_MOCK: "submitFailed/mock",

  PTE_VIDEOS: "get-stgy-videos",
  PREDICTION_DATA: "prediction/list",
  TEMPLATE_DATA: "template/list?skip=",
  HELP_DATA: "template/listNew?skip=0&type=1",
  SUBMIT_FEEDBACK: "feedback/app",
  REPORT: "report/question",
  PROGRESS_TRACKER: "progress",
  PROGRESS_DETAIL: "progress",
  TESTED_EXAM: "tested/exam",
  MOCK_RESULT: "mock/result?new_format=0",
  EXTENSIVE_MOCK_RESULT: "mock/result?new_format=1",
  MOCK_SCORE: "mock/score/",
  MOCK_ANALYSIS: "mock/resultDetail/",
  MOCK_TUTOR_FEEDBACK: "mock/resultDetail/",
  MOCK_VIEW_FEEDBACK: "mock/resultDetail/",

  ADD_NOTES: "add/note",
  SHOW_NOTES: "show/notes",
  DELETE_NOTE: "delete/note",
  DELETE_ME: "delete/question/responseNew",
  SHOW_HISTORY: "show/history",
  SHOW_COMMENT: "show/comment",
  ADD_COMMENT: "add/question/comment",
  DELETE_COMMENT: "delete/question/comment",

  LIVE_SESSIONS: "get/session-wl",
  PTE_CORE_LIVE_SESSIONS: "get/session",
  SAVE_TASK: "save-task",
  GET_TASKS: "get-task",
  DAILY_REPORT: "mock/daily-report",
  GET_NOTIFICATIONS: "getNotifications",
  MARK_AS_READ: "markNotificationAsRead",
  DELETE_NOTIFICATION: "markNotificationAsRead",
  CATEGORIES: "categories",
  GET_TOKENS: "getTokens",
  WORD_DEFINITION: "word/definition",
  TEXT_TRANSLATION: "translate/sentence",
  REPORT_QUESTION: "report/question",
  UPDATE_NAME: "update-name",
  CHANGE_PASSWORD: "changePassword",
  SEND_UPDATE_EMAIL_OTP: `${BASE_URL}/send-update-email-otp`,
  UPDATE_USER_EMAIL: `${BASE_URL}/update-user-email`,

  PRACTICE_DETAIL: "practiceDetail",
  SINGLE_PRACTICE_DETAIL: "single/practiceDetail",
  SET_TIMEZONE: "setTimezone",
  ONBOARDING: "onboarding",

  // Subscription / Packages
  GET_PACKAGES: "getPackages",
  CANCEL_SUBSCRIPTION: "cancel-subscription",
};

export default URLS;
