import { StyleSheet } from 'react-native';
import { scale } from './scale';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FC',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: scale(20),
  },
  welcomeCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: scale(16),
    marginHorizontal: scale(16),
    marginTop: scale(16),
    padding: scale(20),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: scale(20),
  },
  welcomeInfo: {
    marginBottom: scale(15),
  },
  welcomeText: {
    fontSize: scale(16),
    fontWeight: 'bold',
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-Bold',
    marginBottom: scale(4),
  },
  welcomeSubtitle: {
    fontSize: scale(11),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  examDateChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#F2F2F7',
    paddingVertical: scale(5),
    paddingHorizontal: scale(10),
    borderRadius: scale(12),
    marginTop: scale(8),
  },
  examDateChipText: {
    fontSize: scale(10.5),
    fontWeight: 'bold',
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-Bold',
    marginHorizontal: scale(6),
  },
  welcomeActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  actionButtonPrimary: {
    flex: 1.1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DFFFA0',
    paddingVertical: scale(10),
    borderRadius: scale(12),
    marginRight: scale(8),
  },
  actionTextPrimary: {
    fontSize: scale(10.5),
    fontWeight: 'bold',
    color: '#1A2151',
    marginRight: scale(6),
    fontFamily: 'BricolageGrotesque-Bold',
  },
  actionButtonSecondary: {
    flex: 0.9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F2F2F7',
    paddingVertical: scale(10),
    borderRadius: scale(12),
  },
  actionTextSecondary: {
    fontSize: scale(10.5),
    fontWeight: 'bold',
    color: '#1A2151',
    marginRight: scale(4),
    fontFamily: 'BricolageGrotesque-Bold',
  },
  categoriesGrid: {
    paddingHorizontal: scale(12),
    marginBottom: scale(10),
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: scale(8),
  },
  categoryCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: scale(16),
    padding: scale(14),
    marginHorizontal: scale(4),
    borderWidth: 1,
    borderColor: '#E5E5EA',
  },
  categoryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: scale(8),
  },
  viewRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewText: {
    fontSize: scale(10),
    color: '#8E8E93',
    marginRight: scale(2),
    fontFamily: 'BricolageGrotesque-Regular',
  },
  categoryTitle: {
    fontSize: scale(13),
    fontWeight: 'bold',
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-Bold',
    marginBottom: scale(6),
  },
  countContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginBottom: scale(2),
  },
  boldCount: {
    fontSize: scale(16),
    fontWeight: 'bold',
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  totalCount: {
    fontSize: scale(11),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  categorySubText: {
    fontSize: scale(9.5),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  statsBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: scale(16),
    marginHorizontal: scale(16),
    paddingVertical: scale(12),
    paddingHorizontal: scale(10),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    marginBottom: scale(20),
  },
  statItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(4),
  },
  statIconContainer: {
    width: scale(32),
    height: scale(32),
    borderRadius: scale(8),
    backgroundColor: '#F8F9FC',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: scale(6),
    position: 'relative',
  },
  arrowBadge: {
    position: 'absolute',
    bottom: scale(-2),
    right: scale(-2),
    width: scale(12),
    height: scale(12),
    borderRadius: scale(6),
    justifyContent: 'center',
    alignItems: 'center',
  },
  successBadge: {
    backgroundColor: '#34C759',
  },
  warningBadge: {
    backgroundColor: '#FF9500',
  },
  infoBadge: {
    backgroundColor: '#007AFF',
  },
  statInfo: {
    justifyContent: 'center',
  },
  statValue: {
    fontSize: scale(15),
    fontWeight: 'bold',
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  statLabel: {
    fontSize: scale(9),
    color: '#8E8E93',
    lineHeight: scale(11),
    fontFamily: 'BricolageGrotesque-Regular',
  },
  statsDivider: {
    width: 1,
    height: '60%',
    backgroundColor: '#E5E5EA',
  },
  micBanner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: scale(16),
    marginHorizontal: scale(16),
    paddingVertical: scale(12),
    paddingHorizontal: scale(16),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    marginBottom: scale(20),
  },
  micTitle: {
    fontSize: scale(14),
    fontWeight: 'bold',
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  micButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DFFFA0',
    paddingVertical: scale(6),
    paddingHorizontal: scale(12),
    borderRadius: scale(15),
  },
  micButtonText: {
    fontSize: scale(11),
    fontWeight: 'bold',
    color: '#85B82B',
    marginRight: scale(4),
    fontFamily: 'BricolageGrotesque-SemiBold',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    paddingHorizontal: scale(16),
    marginBottom: scale(10),
  },
  sectionTitle: {
    fontSize: scale(16),
    fontWeight: 'bold',
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  viewAllText: {
    fontSize: scale(11),
    fontWeight: '600',
    color: '#85B82B',
    fontFamily: 'BricolageGrotesque-SemiBold',
  },
  helperLink: {
    fontSize: scale(11),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  classCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: scale(16),
    marginHorizontal: scale(16),
    padding: scale(16),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    marginBottom: scale(20),
  },
  classLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  classIndicator: {
    width: scale(36),
    height: scale(36),
    borderRadius: scale(18),
    backgroundColor: '#E5F1FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: scale(10),
  },
  classDetails: {
    flex: 1,
  },
  className: {
    fontSize: scale(13),
    fontWeight: 'bold',
    color: '#1A2151',
    marginBottom: scale(2),
    fontFamily: 'BricolageGrotesque-Bold',
  },
  classSubtitle: {
    fontSize: scale(10),
    color: '#8E8E93',
    marginBottom: scale(6),
    fontFamily: 'BricolageGrotesque-Regular',
  },
  timerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FC',
    alignSelf: 'flex-start',
    paddingVertical: scale(3),
    paddingHorizontal: scale(8),
    borderRadius: scale(10),
  },
  timerDot: {
    width: scale(6),
    height: scale(6),
    borderRadius: scale(3),
    backgroundColor: '#FF3B30',
    marginRight: scale(5),
  },
  timerText: {
    fontSize: scale(10),
    color: '#555',
    fontWeight: 'bold',
  },
  bookButton: {
    backgroundColor: '#F2F2F7',
    paddingVertical: scale(8),
    paddingHorizontal: scale(15),
    borderRadius: scale(18),
  },
  bookButtonText: {
    fontSize: scale(11),
    fontWeight: 'bold',
    color: '#1c1c1e',
    fontFamily: 'BricolageGrotesque-SemiBold',
  },
  aiScoreCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: scale(16),
    marginHorizontal: scale(16),
    padding: scale(20),
    borderWidth: 1,
    borderColor: '#E5E5EA',
    marginBottom: scale(20),
  },
  aiRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scale(15),
  },
  targetInfo: {
    flex: 1,
    marginLeft: scale(20),
  },
  targetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: scale(8),
  },
  targetLabel: {
    fontSize: scale(12),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  targetValue: {
    fontSize: scale(20),
    fontWeight: 'bold',
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  targetAlert: {
    backgroundColor: '#FFFBEA',
    borderRadius: scale(8),
    padding: scale(10),
    borderWidth: 1,
    borderColor: '#FFE0B2',
  },
  alertText: {
    fontSize: scale(9.5),
    color: '#D97706',
    lineHeight: scale(13),
    fontFamily: 'BricolageGrotesque-Regular',
  },
  alertBold: {
    fontWeight: 'bold',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  breakdownGrid: {
    borderTopWidth: 1,
    borderTopColor: '#F2F2F7',
    paddingTop: scale(15),
  },
  breakdownRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: scale(12),
  },
  breakdownItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FC',
    borderRadius: scale(10),
    paddingVertical: scale(8),
    paddingHorizontal: scale(12),
    marginHorizontal: scale(4),
    borderWidth: 1,
    borderColor: 'transparent',
  },
  chartColumn: {
    alignItems: 'center',
  },
  skillTag: {
    marginTop: scale(8),
    paddingVertical: scale(3),
    paddingHorizontal: scale(10),
    borderRadius: scale(10),
    alignSelf: 'center',
  },
  skillTagText: {
    fontSize: scale(10),
    fontWeight: 'bold',
    fontFamily: 'BricolageGrotesque-Bold',
    letterSpacing: 0.3,
  },
  breakdownLabel: {
    flex: 1,
    fontSize: scale(11),
    color: '#8E8E93',
    marginLeft: scale(8),
    fontFamily: 'BricolageGrotesque-Medium',
  },
  breakdownValue: {
    fontSize: scale(12),
    fontWeight: 'bold',
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  tabsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: scale(16),
    marginBottom: scale(10),
  },
  tabButton: {
    flex: 1,
    paddingVertical: scale(6),
    borderRadius: scale(16),
    backgroundColor: '#F2F2F7',
    marginHorizontal: scale(3),
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabButtonActive: {
    backgroundColor: '#1A2151',
  },
  tabButtonText: {
    fontSize: scale(10),
    fontWeight: '600',
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Medium',
  },
  tabButtonTextActive: {
    color: '#FFFFFF',
  },
  videosContainer: {
    marginBottom: scale(20),
  },
  videosContent: {
    paddingHorizontal: scale(16),
  },
  videoCard: {
    width: scale(160),
    marginRight: scale(12),
  },
  thumbnailContainer: {
    width: '100%',
    height: scale(100),
    borderRadius: scale(12),
    overflow: 'hidden',
    backgroundColor: '#E5E5EA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  thumbnail: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  playBadge: {
    width: scale(32),
    height: scale(32),
    borderRadius: scale(16),
    backgroundColor: 'rgba(26, 33, 81, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  videoTitle: {
    fontSize: scale(11),
    fontWeight: '600',
    color: '#1A2151',
    marginTop: scale(6),
    fontFamily: 'BricolageGrotesque-Medium',
  },
  emptyVideosContainer: {
    paddingVertical: scale(20),
    paddingHorizontal: scale(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyVideosText: {
    fontSize: scale(12),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  helpCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: scale(16),
    marginHorizontal: scale(16),
    marginBottom: scale(20),
    borderWidth: 1,
    borderColor: '#EAECEF',
    overflow: 'hidden',
  },
  helpRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    paddingVertical: scale(14),
  },
  helpIconWrap: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(12),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: scale(14),
  },
  helpTextWrap: {
    flex: 1,
  },
  helpTitle: {
    fontSize: scale(13),
    fontWeight: 'bold',
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-Bold',
    marginBottom: scale(2),
  },
  helpSubtitle: {
    fontSize: scale(11),
    color: '#64748B',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  helpDivider: {
    height: 1,
    backgroundColor: '#F1F5F9',
    marginLeft: scale(70),
  },
  videoModalContainer: {
    flex: 1,
    backgroundColor: '#000000',
    justifyContent: 'center',
  },
  videoModalCloseFloating: {
    position: 'absolute',
    top: scale(50),
    left: scale(16),
    width: scale(40),
    height: scale(40),
    borderRadius: scale(20),
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(13, 17, 43, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: scale(20),
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: scale(24),
    width: '90%',
    padding: scale(20),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 10,
    alignItems: 'center',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: scale(15),
  },
  modalTitle: {
    fontSize: scale(16),
    fontWeight: 'bold',
    color: '#1A2151',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  closeButton: {
    padding: scale(5),
  },
  modalBody: {
    alignItems: 'center',
    marginBottom: scale(20),
    paddingHorizontal: scale(10),
  },
  infoIconWrapper: {
    width: scale(54),
    height: scale(54),
    borderRadius: scale(27),
    backgroundColor: '#F3FBF0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: scale(15),
  },
  modalText: {
    fontSize: scale(14),
    color: '#555555',
    textAlign: 'center',
    lineHeight: scale(20),
    fontFamily: 'BricolageGrotesque-Medium',
  },
  modalCloseButton: {
    backgroundColor: '#1A2151',
    paddingVertical: scale(12),
    width: '100%',
    borderRadius: scale(14),
    alignItems: 'center',
  },
  modalCloseButtonText: {
    color: '#FFFFFF',
    fontSize: scale(13),
    fontWeight: 'bold',
    fontFamily: 'BricolageGrotesque-Bold',
  },
});
