import { StyleSheet } from 'react-native';
import { scale } from './scale';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FC',
  },
  scrollContent: {
    paddingBottom: scale(30),
  },
  avatarSection: {
    alignItems: 'center',
    paddingVertical: scale(20),
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#EAECEF',
  },
  avatar: {
    width: scale(72),
    height: scale(72),
    borderRadius: scale(36),
    marginBottom: scale(8),
  },
  changePicBtn: {
    padding: scale(4),
  },
  changePicText: {
    fontSize: scale(11),
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  formContainer: {
    paddingHorizontal: scale(16),
    marginTop: scale(16),
  },
  inputGroup: {
    marginBottom: scale(14),
  },
  inputLabel: {
    fontSize: scale(11),
    fontWeight: 'bold',
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Bold',
    marginBottom: scale(6),
    marginLeft: scale(4),
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EAECEF',
    borderRadius: scale(10),
    paddingHorizontal: scale(14),
    paddingVertical: scale(10),
    fontSize: scale(13),
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  disabledInput: {
    backgroundColor: '#F0F2F5',
    color: '#8E8E93',
  },
  phoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EAECEF',
    borderRadius: scale(10),
    paddingHorizontal: scale(14),
    height: scale(44),
  },
  countryCodeSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: scale(4),
  },
  countryCodeText: {
    fontSize: scale(13),
    fontFamily: 'BricolageGrotesque-Bold',
    color: '#1C1F2A',
    marginRight: scale(6),
  },
  codeDivider: {
    width: 1,
    height: scale(20),
    backgroundColor: '#EAECEF',
    marginHorizontal: scale(8),
  },
  phoneInput: {
    flex: 1,
    height: '100%',
    fontSize: scale(13),
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Regular',
    padding: 0,
  },
  countryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: scale(14),
    paddingHorizontal: scale(20),
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F7',
  },
  countryFlag: {
    fontSize: scale(18),
    marginRight: scale(10),
  },
  countryName: {
    flex: 1,
    fontSize: scale(14),
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  countryCallingCode: {
    fontSize: scale(14),
    fontWeight: 'bold',
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  pickerTrigger: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EAECEF',
    borderRadius: scale(10),
    paddingHorizontal: scale(14),
    paddingVertical: scale(12),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerTriggerText: {
    fontSize: scale(13),
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  pickerPlaceholderText: {
    color: '#8E8E93',
  },
  updateBtn: {
    backgroundColor: '#94C23C',
    borderRadius: scale(12),
    paddingVertical: scale(14),
    alignItems: 'center',
    marginTop: scale(16),
  },
  updateBtnText: {
    fontSize: scale(14),
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'BricolageGrotesque-Bold',
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: scale(20),
    borderTopRightRadius: scale(20),
    maxHeight: '60%',
    paddingBottom: scale(20),
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: scale(20),
    paddingVertical: scale(16),
    borderBottomWidth: 1,
    borderBottomColor: '#EAECEF',
  },
  modalTitle: {
    fontSize: scale(16),
    fontWeight: 'bold',
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  closeButton: {
    padding: scale(4),
  },
  closeButtonText: {
    fontSize: scale(14),
    fontWeight: 'bold',
    color: '#94C23C',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  searchBarWrapper: {
    paddingHorizontal: scale(20),
    paddingVertical: scale(10),
  },
  searchBar: {
    backgroundColor: '#F2F2F7',
    borderRadius: scale(8),
    paddingHorizontal: scale(12),
    paddingVertical: scale(8),
    fontSize: scale(14),
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  modalScroll: {
    paddingHorizontal: scale(10),
  },
  modalItem: {
    paddingVertical: scale(14),
    paddingHorizontal: scale(16),
    borderRadius: scale(8),
    marginVertical: scale(2),
  },
  selectedModalItem: {
    backgroundColor: '#F5F9E9',
  },
  modalItemText: {
    fontSize: scale(14),
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Regular',
  },
  selectedModalItemText: {
    fontWeight: 'bold',
    color: '#94C23C',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  emailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  emailInput: {
    flex: 1,
  },
  changeEmailBtn: {
    backgroundColor: '#94C23C',
    borderRadius: scale(10),
    paddingHorizontal: scale(12),
    paddingVertical: scale(10),
  },
  changeEmailBtnText: {
    fontSize: scale(12),
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'BricolageGrotesque-Bold',
  },
  modalSubLabel: {
    fontSize: scale(12),
    fontWeight: 'bold',
    color: '#8E8E93',
    fontFamily: 'BricolageGrotesque-Bold',
    marginBottom: scale(6),
  },
  modalInput: {
    backgroundColor: '#F2F2F7',
    borderRadius: scale(10),
    paddingHorizontal: scale(12),
    paddingVertical: scale(10),
    fontSize: scale(14),
    color: '#1C1F2A',
    fontFamily: 'BricolageGrotesque-Regular',
    marginBottom: scale(8),
  },
  modalConfirmBtn: {
    backgroundColor: '#94C23C',
    borderRadius: scale(10),
    paddingVertical: scale(12),
    alignItems: 'center',
    marginTop: scale(8),
  },
  modalConfirmBtnText: {
    fontSize: scale(14),
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'BricolageGrotesque-Bold',
  },
});
